/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertDialog: typeof import('./src/components/dialog/AlertDialog.vue')['default']
    BaseDialog: typeof import('./src/components/dialog/BaseDialog.vue')['default']
    BasicSection: typeof import('./src/components/basic/BasicSection.vue')['default']
    ClickableCard: typeof import('./src/components/basic/ClickableCard.vue')['default']
    ConfirmDialog: typeof import('./src/components/dialog/ConfirmDialog.vue')['default']
    FileDropper: typeof import('./src/components/upload/FileDropper.vue')['default']
    FileGrid: typeof import('./src/components/listing/FileGrid.vue')['default']
    FileTable: typeof import('./src/components/listing/FileTable.vue')['default']
    FolderGrid: typeof import('./src/components/listing/FolderGrid.vue')['default']
    FolderTable: typeof import('./src/components/listing/FolderTable.vue')['default']
    GrayHighlightButton: typeof import('./src/components/basic/GrayHighlightButton.vue')['default']
    HighlightButton: typeof import('./src/components/basic/HighlightButton.vue')['default']
    HoverUnderlineText: typeof import('./src/components/basic/HoverUnderlineText.vue')['default']
    ImagePreview: typeof import('./src/components/ImagePreview.vue')['default']
    ListingError: typeof import('./src/components/listing/ListingError.vue')['default']
    ListingTypeChooser: typeof import('./src/components/listing/ListingTypeChooser.vue')['default']
    ListingWrapper: typeof import('./src/components/ListingWrapper.vue')['default']
    LoginDialog: typeof import('./src/components/dialog/LoginDialog.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PathRenderer: typeof import('./src/components/PathRenderer.vue')['default']
    ProgressBar: typeof import('./src/components/basic/ProgressBar.vue')['default']
    RenameActionDialog: typeof import('./src/components/dialog/RenameActionDialog.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SidebarSizeChart: typeof import('./src/components/SidebarSizeChart.vue')['default']
    SortableTable: typeof import('./src/components/SortableTable.vue')['default']
    StyledButton: typeof import('./src/components/basic/StyledButton.vue')['default']
    SubfolderList: typeof import('./src/components/SubfolderList.vue')['default']
    ThumbnailFile: typeof import('./src/components/listing/ThumbnailFile.vue')['default']
    ThumbnailFileGrid: typeof import('./src/components/listing/ThumbnailFileGrid.vue')['default']
    UploadDropOverlay: typeof import('./src/components/overlay/UploadDropOverlay.vue')['default']
    UploadProgressRenderer: typeof import('./src/components/upload/UploadProgressRenderer.vue')['default']
    UploadRenderer: typeof import('./src/components/upload/UploadRenderer.vue')['default']
    UploadsDialog: typeof import('./src/components/dialog/UploadsDialog.vue')['default']
    UploadSubmitDialog: typeof import('./src/components/dialog/UploadSubmitDialog.vue')['default']
  }
}
