/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertDialog: typeof import('./src/components/dialog/AlertDialog.vue')['default']
    BaseDialog: typeof import('./src/components/dialog/BaseDialog.vue')['default']
    BasicSection: typeof import('./src/components/basic/BasicSection.vue')['default']
    ClickableCard: typeof import('./src/components/basic/ClickableCard.vue')['default']
    ConfirmDialog: typeof import('./src/components/dialog/ConfirmDialog.vue')['default']
    FileDropper: typeof import('./src/components/upload/FileDropper.vue')['default']
    FileGrid: typeof import('./src/components/listing/FileGrid.vue')['default']
    FileTable: typeof import('./src/components/FileTable.vue')['default']
    FolderGrid: typeof import('./src/components/listing/FolderGrid.vue')['default']
    HoverUnderlineText: typeof import('./src/components/basic/HoverUnderlineText.vue')['default']
    ImagePreview: typeof import('./src/components/ImagePreview.vue')['default']
    LoginDialog: typeof import('./src/components/dialog/LoginDialog.vue')['default']
    PathRenderer: typeof import('./src/components/PathRenderer.vue')['default']
    RenameActionDialog: typeof import('./src/components/dialog/RenameActionDialog.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SortableTable: typeof import('./src/components/SortableTable.vue')['default']
    StyledButton: typeof import('./src/components/basic/StyledButton.vue')['default']
    SubfolderList: typeof import('./src/components/SubfolderList.vue')['default']
    SubfolderTable: typeof import('./src/components/SubfolderTable.vue')['default']
    ThumbnailFileGrid: typeof import('./src/components/listing/ThumbnailFileGrid.vue')['default']
    UploadDropOverlay: typeof import('./src/components/overlay/UploadDropOverlay.vue')['default']
    UploadProgressRenderer: typeof import('./src/components/upload/UploadProgressRenderer.vue')['default']
    UploadRenderer: typeof import('./src/components/upload/UploadRenderer.vue')['default']
    UploadSubmitDialog: typeof import('./src/components/dialog/UploadSubmitDialog.vue')['default']
  }
}
